services:
  farmis_prod_server:
    build:
      context: .
      dockerfile: ./docker/farmis_server/Dockerfile.prod
    command: gunicorn farmis.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - farmis_prod_server_static_volume:/home/app/web/staticfiles
      - farmis_prod_server_media_volume:/home/app/web/mediafiles
    secrets:
      - farmis-prod-server-secret-key
      - postgresql-prod-user-password
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - farmis_prod_db
      - farmis_prod_redis
  farmis_prod_db:
    image: postgres:16-alpine
    volumes:
      - farmis_prod_db_data:/var/lib/postgresql/data/
    secrets:
      - farmis-prod-db-password
    env_file:
      - ./.env.prod.db
  farmis_prod_nginx:
    build:
      context: ./docker/farmis_nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - farmis_prod_server_static_volume:/home/app/web/staticfiles
      - farmis_prod_server_media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - farmis_prod_server
  farmis_prod_redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379

  
volumes:
  farmis_prod_db_data:
  farmis_prod_server_static_volume:
  farmis_prod_server_media_volume:

secrets:
  farmis-prod-db-password:
    file: docker_compose/farmis_db/secrets/password.txt
  farmis-prod-server-secret-key:
    file: docker_compose/farmis_server/secrets/secret_key.txt
  postgresql-prod-user-password:
    file: docker_compose/farmis_server/secrets/postgresql_user_password.txt