# Generated by Django 5.1.1 on 2024-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='crops_grown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
