# Generated by Django 5.1.1 on 2024-09-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_farmerprofile_crops_grown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
