# Generated by Django 5.1.1 on 2024-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('farmer', 'Farmer'), ('researcher', 'Researcher'), ('investor', 'Investor'), ('gov', 'Government Agency'), ('ngo', 'Non-Governmental Organization'), ('provider', 'Service Provider')], default='generic', max_length=20),
        ),
    ]
